stack=[]
stack.append("a")
stack.append("b")
stack.append("c")
print("After Append the value to the stack")
print(stack)
print(stack.pop())
print(stack.pop())
print(stack.pop())
print("After Elements are poped")
print(stack)
